/*
Billsby API

Billsby is a feature-rich \"Saas\" recurring payment platform, ranked as the leading subscription billing software by G2.

Billsby is designed to ensure customers can go live quickly, often within 1-2 hours.  To help facilitate this process we have a team of friendly knowledgeable advisors ready to help your business go live.    

Billsby specializes in providing great customer service at an affordable price point - our technology is rated No 1 on G2 by our customers.

If you are a developer creating a solution for your customer, Billsby has a friendly well-documented API.  The Billsby team are here to provide support to developers in order to ensure a smooth migration or new system build. 

Why not book a call, talk through your Billing requirements and we can let you know how we can help you transform your business..

The version of the OpenAPI document: 1.3.5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CustomerAddSubscriptionToExistingCustomerRequestAddOnsInner } from './customer-add-subscription-to-existing-customer-request-add-ons-inner';
import { CustomerAddSubscriptionToExistingCustomerRequestAddress } from './customer-add-subscription-to-existing-customer-request-address';
import { CustomerAddSubscriptionToExistingCustomerRequestCouponCodesInner } from './customer-add-subscription-to-existing-customer-request-coupon-codes-inner';
import { CustomerAddSubscriptionToExistingCustomerRequestCustomFieldResponseInner } from './customer-add-subscription-to-existing-customer-request-custom-field-response-inner';

/**
 * 
 * @export
 * @interface CustomerAddSubscriptionToExistingCustomerRequest
 */
export interface CustomerAddSubscriptionToExistingCustomerRequest {
    /**
     * The unique identifier of the cycle in the Billsby platform
     * @type {number}
     * @memberof CustomerAddSubscriptionToExistingCustomerRequest
     */
    'cycleId': number;
    /**
     * The number of units for unit based plans
     * @type {number}
     * @memberof CustomerAddSubscriptionToExistingCustomerRequest
     */
    'units'?: number;
    /**
     * 
     * @type {CustomerAddSubscriptionToExistingCustomerRequestAddress}
     * @memberof CustomerAddSubscriptionToExistingCustomerRequest
     */
    'address'?: CustomerAddSubscriptionToExistingCustomerRequestAddress;
    /**
     * The shipping address of the customer
     * @type {object}
     * @memberof CustomerAddSubscriptionToExistingCustomerRequest
     */
    'shippingAddress'?: object;
    /**
     * Any additional email addresses given by the customer
     * @type {string}
     * @memberof CustomerAddSubscriptionToExistingCustomerRequest
     */
    'additionalEmail'?: string;
    /**
     * The country associated with the phone number
     * @type {string}
     * @memberof CustomerAddSubscriptionToExistingCustomerRequest
     */
    'phoneNumberDialCountry'?: string;
    /**
     * The country dial code for the customer phone number
     * @type {number}
     * @memberof CustomerAddSubscriptionToExistingCustomerRequest
     */
    'phoneNumberDialCode'?: number;
    /**
     * The customer\'s phone number
     * @type {number}
     * @memberof CustomerAddSubscriptionToExistingCustomerRequest
     */
    'phoneNumber'?: number;
    /**
     * Gas the customer given marketing consent: true or false
     * @type {boolean}
     * @memberof CustomerAddSubscriptionToExistingCustomerRequest
     */
    'marketingConsent'?: boolean;
    /**
     * Tax registration number
     * @type {string}
     * @memberof CustomerAddSubscriptionToExistingCustomerRequest
     */
    'taxRegNumber'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerAddSubscriptionToExistingCustomerRequest
     */
    'ipAddress'?: string;
    /**
     * Any responses to custom fields
     * @type {Array<CustomerAddSubscriptionToExistingCustomerRequestCustomFieldResponseInner>}
     * @memberof CustomerAddSubscriptionToExistingCustomerRequest
     */
    'customFieldResponse'?: Array<CustomerAddSubscriptionToExistingCustomerRequestCustomFieldResponseInner>;
    /**
     * Any add-ons to be included in the plan, along with the quantity of each add-on if unit based
     * @type {Array<CustomerAddSubscriptionToExistingCustomerRequestAddOnsInner>}
     * @memberof CustomerAddSubscriptionToExistingCustomerRequest
     */
    'addOns'?: Array<CustomerAddSubscriptionToExistingCustomerRequestAddOnsInner>;
    /**
     * Any allowances to be included with the plan
     * @type {number}
     * @memberof CustomerAddSubscriptionToExistingCustomerRequest
     */
    'allowances'?: number;
    /**
     * The coupon code to be used for the plan
     * @type {Array<CustomerAddSubscriptionToExistingCustomerRequestCouponCodesInner>}
     * @memberof CustomerAddSubscriptionToExistingCustomerRequest
     */
    'couponCodes'?: Array<CustomerAddSubscriptionToExistingCustomerRequestCouponCodesInner>;
}

