/*
Billsby API

Billsby is a feature-rich \"Saas\" recurring payment platform, ranked as the leading subscription billing software by G2.

Billsby is designed to ensure customers can go live quickly, often within 1-2 hours.  To help facilitate this process we have a team of friendly knowledgeable advisors ready to help your business go live.    

Billsby specializes in providing great customer service at an affordable price point - our technology is rated No 1 on G2 by our customers.

If you are a developer creating a solution for your customer, Billsby has a friendly well-documented API.  The Billsby team are here to provide support to developers in order to ensure a smooth migration or new system build. 

Why not book a call, talk through your Billing requirements and we can let you know how we can help you transform your business..

The version of the OpenAPI document: 1.3.5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CustomerCreateWithoutSubscriptionRequestCardDetails
 */
export interface CustomerCreateWithoutSubscriptionRequestCardDetails {
    /**
     * The full name of the customer
     * @type {string}
     * @memberof CustomerCreateWithoutSubscriptionRequestCardDetails
     */
    'fullName'?: string;
    /**
     * This can be found in the create token API response
     * @type {string}
     * @memberof CustomerCreateWithoutSubscriptionRequestCardDetails
     */
    'paymentCardToken'?: string;
    /**
     * Customers two digit expiry month - i.e. \"12\"
     * @type {number}
     * @memberof CustomerCreateWithoutSubscriptionRequestCardDetails
     */
    'expiryMonth'?: number;
    /**
     * Customers card expiry year - i.e. \"2020\"
     * @type {number}
     * @memberof CustomerCreateWithoutSubscriptionRequestCardDetails
     */
    'expiryYear'?: number;
    /**
     * \"visa\" \"master\" \"american_express\"
     * @type {string}
     * @memberof CustomerCreateWithoutSubscriptionRequestCardDetails
     */
    'cardType'?: string;
    /**
     * The last 4 digits of the customers card
     * @type {string}
     * @memberof CustomerCreateWithoutSubscriptionRequestCardDetails
     */
    'last4Digits'?: string;
}

