/*
Billsby API

Billsby is a feature-rich \"Saas\" recurring payment platform, ranked as the leading subscription billing software by G2.

Billsby is designed to ensure customers can go live quickly, often within 1-2 hours.  To help facilitate this process we have a team of friendly knowledgeable advisors ready to help your business go live.    

Billsby specializes in providing great customer service at an affordable price point - our technology is rated No 1 on G2 by our customers.

If you are a developer creating a solution for your customer, Billsby has a friendly well-documented API.  The Billsby team are here to provide support to developers in order to ensure a smooth migration or new system build. 

Why not book a call, talk through your Billing requirements and we can let you know how we can help you transform your business..

The version of the OpenAPI document: 1.3.5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CustomerAddSubscriptionToExistingCustomerRequestAddOnsInner } from './customer-add-subscription-to-existing-customer-request-add-ons-inner';
import { CustomerAddSubscriptionToExistingCustomerRequestCouponCodesInner } from './customer-add-subscription-to-existing-customer-request-coupon-codes-inner';
import { CustomerAddSubscriptionToExistingCustomerRequestCustomFieldResponseInner } from './customer-add-subscription-to-existing-customer-request-custom-field-response-inner';
import { CustomerCreateNewCustomerAndSubscriptionRequestAddress } from './customer-create-new-customer-and-subscription-request-address';
import { CustomerCreateNewCustomerAndSubscriptionRequestCardDetails } from './customer-create-new-customer-and-subscription-request-card-details';
import { CustomerCreateNewCustomerAndSubscriptionRequestShippingAddress } from './customer-create-new-customer-and-subscription-request-shipping-address';

/**
 * 
 * @export
 * @interface CustomerCreateNewCustomerAndSubscriptionRequest
 */
export interface CustomerCreateNewCustomerAndSubscriptionRequest {
    /**
     * The customer\'s first name
     * @type {string}
     * @memberof CustomerCreateNewCustomerAndSubscriptionRequest
     */
    'firstName': string;
    /**
     * The customer\'s last name
     * @type {string}
     * @memberof CustomerCreateNewCustomerAndSubscriptionRequest
     */
    'lastName': string;
    /**
     * The customer\'s email address
     * @type {string}
     * @memberof CustomerCreateNewCustomerAndSubscriptionRequest
     */
    'email': string;
    /**
     * The unique identifier of the cycle in Billsby
     * @type {number}
     * @memberof CustomerCreateNewCustomerAndSubscriptionRequest
     */
    'cycleId': number;
    /**
     * The number of units included in the subscription (min. 1)
     * @type {number}
     * @memberof CustomerCreateNewCustomerAndSubscriptionRequest
     */
    'Units': number;
    /**
     * 
     * @type {CustomerCreateNewCustomerAndSubscriptionRequestAddress}
     * @memberof CustomerCreateNewCustomerAndSubscriptionRequest
     */
    'address': CustomerCreateNewCustomerAndSubscriptionRequestAddress;
    /**
     * 
     * @type {CustomerCreateNewCustomerAndSubscriptionRequestShippingAddress}
     * @memberof CustomerCreateNewCustomerAndSubscriptionRequest
     */
    'shippingAddress'?: CustomerCreateNewCustomerAndSubscriptionRequestShippingAddress;
    /**
     * Any additional email address provided by the customer
     * @type {string}
     * @memberof CustomerCreateNewCustomerAndSubscriptionRequest
     */
    'additionalEmail'?: string;
    /**
     * The country associated with their phone number
     * @type {string}
     * @memberof CustomerCreateNewCustomerAndSubscriptionRequest
     */
    'phoneNumberDialCountry'?: string;
    /**
     * The country code associated with their phone number
     * @type {number}
     * @memberof CustomerCreateNewCustomerAndSubscriptionRequest
     */
    'phoneNumberDialCode'?: number;
    /**
     * The customer\'s phone number. If phoneNumber is provided, then phoneNumberDialCountry and phoneNumberDialCode are required.
     * @type {number}
     * @memberof CustomerCreateNewCustomerAndSubscriptionRequest
     */
    'phoneNumber'?: number;
    /**
     * Has the customer given marketing consent; true or false
     * @type {boolean}
     * @memberof CustomerCreateNewCustomerAndSubscriptionRequest
     */
    'marketingConsent'?: boolean;
    /**
     * Response to any custom field questions you want to add to the subscription
     * @type {Array<CustomerAddSubscriptionToExistingCustomerRequestCustomFieldResponseInner>}
     * @memberof CustomerCreateNewCustomerAndSubscriptionRequest
     */
    'customFieldResponse'?: Array<CustomerAddSubscriptionToExistingCustomerRequestCustomFieldResponseInner>;
    /**
     * The add-ons that you want to include in the subscription
     * @type {Array<CustomerAddSubscriptionToExistingCustomerRequestAddOnsInner>}
     * @memberof CustomerCreateNewCustomerAndSubscriptionRequest
     */
    'addOns'?: Array<CustomerAddSubscriptionToExistingCustomerRequestAddOnsInner>;
    /**
     * The IDs of any allowances you want to include in the subscription. For multiple allowances you can add the IDs separated by a comma
     * @type {Array<number>}
     * @memberof CustomerCreateNewCustomerAndSubscriptionRequest
     */
    'allowances'?: Array<number>;
    /**
     * The codes of any coupons you want to apply to the subscription
     * @type {Array<CustomerAddSubscriptionToExistingCustomerRequestCouponCodesInner>}
     * @memberof CustomerCreateNewCustomerAndSubscriptionRequest
     */
    'couponCodes'?: Array<CustomerAddSubscriptionToExistingCustomerRequestCouponCodesInner>;
    /**
     * 
     * @type {CustomerCreateNewCustomerAndSubscriptionRequestCardDetails}
     * @memberof CustomerCreateNewCustomerAndSubscriptionRequest
     */
    'cardDetails': CustomerCreateNewCustomerAndSubscriptionRequestCardDetails;
}

