/*
Billsby API

Billsby is a feature-rich \"Saas\" recurring payment platform, ranked as the leading subscription billing software by G2.

Billsby is designed to ensure customers can go live quickly, often within 1-2 hours.  To help facilitate this process we have a team of friendly knowledgeable advisors ready to help your business go live.    

Billsby specializes in providing great customer service at an affordable price point - our technology is rated No 1 on G2 by our customers.

If you are a developer creating a solution for your customer, Billsby has a friendly well-documented API.  The Billsby team are here to provide support to developers in order to ensure a smooth migration or new system build. 

Why not book a call, talk through your Billing requirements and we can let you know how we can help you transform your business..

The version of the OpenAPI document: 1.3.5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { InvoiceDetailsResponseSubscriptionsInner } from './invoice-details-response-subscriptions-inner';

/**
 * 
 * @export
 * @interface InvoiceDetailsResponse
 */
export interface InvoiceDetailsResponse {
    /**
     * 
     * @type {string}
     * @memberof InvoiceDetailsResponse
     */
    'invoiceId'?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceDetailsResponse
     */
    'customerEmail'?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceDetailsResponse
     */
    'customerFirstName'?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceDetailsResponse
     */
    'customerLastName'?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceDetailsResponse
     */
    'customerUniqueId'?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceDetailsResponse
     */
    'addressLine1'?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceDetailsResponse
     */
    'addressLine2'?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceDetailsResponse
     */
    'addressPostCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceDetailsResponse
     */
    'addressCity'?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceDetailsResponse
     */
    'addressState'?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceDetailsResponse
     */
    'addressCountry'?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceDetailsResponse
     */
    'addressCountryCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceDetailsResponse
     */
    'invoiceNumber'?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceDetailsResponse
     */
    'createdOn'?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceDetailsResponse
     */
    'formattedAmount'?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceDetailsResponse
     */
    'amount'?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceDetailsResponse
     */
    'currency'?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceDetailsResponse
     */
    'status'?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceDetailsResponse
     */
    'subTotal'?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceDetailsResponse
     */
    'taxTotal'?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceDetailsResponse
     */
    'prorationAdjustment'?: string;
    /**
     * 
     * @type {any}
     * @memberof InvoiceDetailsResponse
     */
    'prorationFactor'?: any;
    /**
     * 
     * @type {Array<any>}
     * @memberof InvoiceDetailsResponse
     */
    'taxes'?: Array<any>;
    /**
     * 
     * @type {string}
     * @memberof InvoiceDetailsResponse
     */
    'invoiceType'?: string;
    /**
     * 
     * @type {Array<InvoiceDetailsResponseSubscriptionsInner>}
     * @memberof InvoiceDetailsResponse
     */
    'subscriptions'?: Array<InvoiceDetailsResponseSubscriptionsInner>;
    /**
     * 
     * @type {string}
     * @memberof InvoiceDetailsResponse
     */
    'companyName'?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceDetailsResponse
     */
    'companyEmail'?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceDetailsResponse
     */
    'companyTaxNumber'?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceDetailsResponse
     */
    'companyDomain'?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceDetailsResponse
     */
    'companyPhoneNumberDialCountry'?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceDetailsResponse
     */
    'companyPhoneNumberDialCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceDetailsResponse
     */
    'companyPhoneNumber'?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceDetailsResponse
     */
    'companyAddressLine1'?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceDetailsResponse
     */
    'companyAddressLine2'?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceDetailsResponse
     */
    'companyCity'?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceDetailsResponse
     */
    'companyState'?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceDetailsResponse
     */
    'companyPostCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceDetailsResponse
     */
    'companyCountry'?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceDetailsResponse
     */
    'brandingLogo'?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceDetailsResponse
     */
    'brandingLogoBackgroundColor'?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceDetailsResponse
     */
    'brandingHighlightColor'?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceDetailsResponse
     */
    'supportUrl'?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceDetailsResponse
     */
    'cardType'?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceDetailsResponse
     */
    'cardLast4Digits'?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceDetailsResponse
     */
    'cardExpiryMonth'?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceDetailsResponse
     */
    'cardExpiryYear'?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceDetailsResponse
     */
    'refundableAmount'?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceDetailsResponse
     */
    'footerCompanyName'?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceDetailsResponse
     */
    'footerAddressLine1'?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceDetailsResponse
     */
    'footerAddressLine2'?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceDetailsResponse
     */
    'footerAddressState'?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceDetailsResponse
     */
    'footerAddressCity'?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceDetailsResponse
     */
    'footerAddressPostCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceDetailsResponse
     */
    'footerAddressCountryISO3'?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceDetailsResponse
     */
    'footerEmailAddress'?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceDetailsResponse
     */
    'footerPhoneNumberDialCountry'?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceDetailsResponse
     */
    'footerPhoneNumberDialCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceDetailsResponse
     */
    'footerPhoneNumber'?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceDetailsResponse
     */
    'supportContactHeading'?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceDetailsResponse
     */
    'supportContactContent'?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceDetailsResponse
     */
    'supportContactSupportUrl'?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceDetailsResponse
     */
    'supportContactSupportUrlButtonText'?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceDetailsResponse
     */
    'isAdvertEnabled'?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceDetailsResponse
     */
    'advertImageUrl'?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceDetailsResponse
     */
    'advertLinkToUrl'?: string;
}

