/*
Billsby API

Billsby is a feature-rich \"Saas\" recurring payment platform, ranked as the leading subscription billing software by G2.

Billsby is designed to ensure customers can go live quickly, often within 1-2 hours.  To help facilitate this process we have a team of friendly knowledgeable advisors ready to help your business go live.    

Billsby specializes in providing great customer service at an affordable price point - our technology is rated No 1 on G2 by our customers.

If you are a developer creating a solution for your customer, Billsby has a friendly well-documented API.  The Billsby team are here to provide support to developers in order to ensure a smooth migration or new system build. 

Why not book a call, talk through your Billing requirements and we can let you know how we can help you transform your business..

The version of the OpenAPI document: 1.3.5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ProductCreatePlanRequest
 */
export interface ProductCreatePlanRequest {
    /**
     * The description of the plan
     * @type {string}
     * @memberof ProductCreatePlanRequest
     */
    'description'?: string;
    /**
     * The name of the plan you want to add
     * @type {string}
     * @memberof ProductCreatePlanRequest
     */
    'name'?: string;
    /**
     * The display name of the plan
     * @type {string}
     * @memberof ProductCreatePlanRequest
     */
    'displayName'?: string;
    /**
     * The type of pricing model for the plan; FlatFee = 1, PerUnit = 2, Reserved = 3, Tiered = 4, Volume = 5, Ranged = 6
     * @type {number}
     * @memberof ProductCreatePlanRequest
     */
    'pricingModel'?: number;
    /**
     * Any feature tags you want to add to the plan
     * @type {string}
     * @memberof ProductCreatePlanRequest
     */
    'featureTags'?: string;
    /**
     * The type of visibility of each plan; public, hidden and on-sale. Available values: 0, 1, 2, 3 (Public=0, Hidden=1, Internal=2, OffSale=3)
     * @type {number}
     * @memberof ProductCreatePlanRequest
     */
    'visibility'?: number;
    /**
     * The URL you want to redirect your customers to when they have completed the checkout flow
     * @type {string}
     * @memberof ProductCreatePlanRequest
     */
    'redirectUrl'?: string;
    /**
     * The email you would like to receive an alert when a customer signs up for this plan
     * @type {string}
     * @memberof ProductCreatePlanRequest
     */
    'alertEmail'?: string;
}

