/*
Billsby API

Billsby is a feature-rich \"Saas\" recurring payment platform, ranked as the leading subscription billing software by G2.

Billsby is designed to ensure customers can go live quickly, often within 1-2 hours.  To help facilitate this process we have a team of friendly knowledgeable advisors ready to help your business go live.    

Billsby specializes in providing great customer service at an affordable price point - our technology is rated No 1 on G2 by our customers.

If you are a developer creating a solution for your customer, Billsby has a friendly well-documented API.  The Billsby team are here to provide support to developers in order to ensure a smooth migration or new system build. 

Why not book a call, talk through your Billing requirements and we can let you know how we can help you transform your business..

The version of the OpenAPI document: 1.3.5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ProductCreateCycleRequestCyclesInputModelInnerTiersInner } from './product-create-cycle-request-cycles-input-model-inner-tiers-inner';

/**
 * 
 * @export
 * @interface ProductCreateCycleRequestCyclesInputModelInner
 */
export interface ProductCreateCycleRequestCyclesInputModelInner {
    /**
     * A number with the update frequency (for example: 5 to renew every five of frequencyType)
     * @type {number}
     * @memberof ProductCreateCycleRequestCyclesInputModelInner
     */
    'frequency': number;
    /**
     * Daily = 1, Weekly = 2, Monthly = 3, Yearly = 4
     * @type {number}
     * @memberof ProductCreateCycleRequestCyclesInputModelInner
     */
    'frequencyType': number;
    /**
     * The price amount of this cycle (unused in tiered based cycles)
     * @type {number}
     * @memberof ProductCreateCycleRequestCyclesInputModelInner
     */
    'price': number;
    /**
     * Anniversary = 1, FixedDayEachMonth = 2, FixedDayOfTheWeek = 3
     * @type {number}
     * @memberof ProductCreateCycleRequestCyclesInputModelInner
     */
    'billingDateType': number;
    /**
     * The type of visibility of each product; public, hidden and on-sale. Available values: 0, 1, 2, 3 (Public=0, Hidden=1, Internal=2, OffSale=3)
     * @type {number}
     * @memberof ProductCreateCycleRequestCyclesInputModelInner
     */
    'visibility': number;
    /**
     * A number with the amount of free trial (for example: 5 for five of frequencyType of free trial)
     * @type {number}
     * @memberof ProductCreateCycleRequestCyclesInputModelInner
     */
    'freeTrial'?: number;
    /**
     * Daily = 1, Weekly = 2, Monthly = 3, Yearly = 4
     * @type {number}
     * @memberof ProductCreateCycleRequestCyclesInputModelInner
     */
    'freeTrialFrequencyType'?: number;
    /**
     * A number with the amount of minimum contract term (for example: 5 for five of frequencyType of minimum term)
     * @type {number}
     * @memberof ProductCreateCycleRequestCyclesInputModelInner
     */
    'contractTerm'?: number;
    /**
     * Daily = 1, Weekly = 2, Monthly = 3, Yearly = 4
     * @type {number}
     * @memberof ProductCreateCycleRequestCyclesInputModelInner
     */
    'contractTermFrequencyType'?: number;
    /**
     * The price amount of setup fee (charged only on first invoice of new subscriptions)
     * @type {number}
     * @memberof ProductCreateCycleRequestCyclesInputModelInner
     */
    'setupFeePrice'?: number;
    /**
     * The amount of free units in tiered based cycles
     * @type {number}
     * @memberof ProductCreateCycleRequestCyclesInputModelInner
     */
    'freeQuantity'?: number;
    /**
     * The fixed billing date if there is one (from 1 to 28)
     * @type {number}
     * @memberof ProductCreateCycleRequestCyclesInputModelInner
     */
    'fixedBillingDateDay'?: number;
    /**
     * The fixed billing month if there is one (from 1 to 12)
     * @type {number}
     * @memberof ProductCreateCycleRequestCyclesInputModelInner
     */
    'fixedBillingDateMonth'?: number;
    /**
     * DoNotProRate = 1, DoNotChargeUntilNextCycle = 2, ProRateBasedOnDaysRemaining = 3
     * @type {number}
     * @memberof ProductCreateCycleRequestCyclesInputModelInner
     */
    'proRateOption'?: number;
    /**
     * Define your tiers
     * @type {Array<ProductCreateCycleRequestCyclesInputModelInnerTiersInner>}
     * @memberof ProductCreateCycleRequestCyclesInputModelInner
     */
    'tiers'?: Array<ProductCreateCycleRequestCyclesInputModelInnerTiersInner>;
}

