/*
Billsby API

Billsby is a feature-rich \"Saas\" recurring payment platform, ranked as the leading subscription billing software by G2.

Billsby is designed to ensure customers can go live quickly, often within 1-2 hours.  To help facilitate this process we have a team of friendly knowledgeable advisors ready to help your business go live.    

Billsby specializes in providing great customer service at an affordable price point - our technology is rated No 1 on G2 by our customers.

If you are a developer creating a solution for your customer, Billsby has a friendly well-documented API.  The Billsby team are here to provide support to developers in order to ensure a smooth migration or new system build. 

Why not book a call, talk through your Billing requirements and we can let you know how we can help you transform your business..

The version of the OpenAPI document: 1.3.5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ProductCreatePlanResponseCyclesInner } from './product-create-plan-response-cycles-inner';

/**
 * 
 * @export
 * @interface ProductCreatePlanResponse
 */
export interface ProductCreatePlanResponse {
    /**
     * 
     * @type {string}
     * @memberof ProductCreatePlanResponse
     */
    'description'?: string;
    /**
     * 
     * @type {number}
     * @memberof ProductCreatePlanResponse
     */
    'planId'?: number;
    /**
     * 
     * @type {string}
     * @memberof ProductCreatePlanResponse
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductCreatePlanResponse
     */
    'displayName'?: string;
    /**
     * 
     * @type {number}
     * @memberof ProductCreatePlanResponse
     */
    'pricingModelType'?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductCreatePlanResponse
     */
    'productId'?: number;
    /**
     * 
     * @type {Array<ProductCreatePlanResponseCyclesInner>}
     * @memberof ProductCreatePlanResponse
     */
    'cycles'?: Array<ProductCreatePlanResponseCyclesInner>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ProductCreatePlanResponse
     */
    'featureTags'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ProductCreatePlanResponse
     */
    'visibility'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductCreatePlanResponse
     */
    'redirectUrl'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ProductCreatePlanResponse
     */
    'hasActiveSubscription'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ProductCreatePlanResponse
     */
    'alertEmail'?: string;
}

