/*
Billsby API

Billsby is a feature-rich \"Saas\" recurring payment platform, ranked as the leading subscription billing software by G2.

Billsby is designed to ensure customers can go live quickly, often within 1-2 hours.  To help facilitate this process we have a team of friendly knowledgeable advisors ready to help your business go live.    

Billsby specializes in providing great customer service at an affordable price point - our technology is rated No 1 on G2 by our customers.

If you are a developer creating a solution for your customer, Billsby has a friendly well-documented API.  The Billsby team are here to provide support to developers in order to ensure a smooth migration or new system build. 

Why not book a call, talk through your Billing requirements and we can let you know how we can help you transform your business..

The version of the OpenAPI document: 1.3.5


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ProductCreateCycleResponseInnerPricingModel
 */
export interface ProductCreateCycleResponseInnerPricingModel {
    /**
     * 
     * @type {number}
     * @memberof ProductCreateCycleResponseInnerPricingModel
     */
    'pricingModelId'?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductCreateCycleResponseInnerPricingModel
     */
    'frequency'?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductCreateCycleResponseInnerPricingModel
     */
    'frequencyType'?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductCreateCycleResponseInnerPricingModel
     */
    'freeTrial'?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductCreateCycleResponseInnerPricingModel
     */
    'freeTrialFrequencyType'?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductCreateCycleResponseInnerPricingModel
     */
    'contractTerm'?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductCreateCycleResponseInnerPricingModel
     */
    'contractTermFrequencyType'?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductCreateCycleResponseInnerPricingModel
     */
    'setupFeePrice'?: number;
    /**
     * 
     * @type {string}
     * @memberof ProductCreateCycleResponseInnerPricingModel
     */
    'setupFeePriceFormatted'?: string;
    /**
     * 
     * @type {number}
     * @memberof ProductCreateCycleResponseInnerPricingModel
     */
    'freeQuantity'?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductCreateCycleResponseInnerPricingModel
     */
    'billingDateType'?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductCreateCycleResponseInnerPricingModel
     */
    'fixedBillingDateDay'?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductCreateCycleResponseInnerPricingModel
     */
    'proRateOption'?: number;
}

